### PR TITLE
Reintroduce re-exports in `rhai::plugin`

### LINKED ISSUE #11: could not be complied with new version of rhai
could not be complied with new version of rhai.   It sounds  many error.

### LINKED ISSUE #12: Cannot Compile with Rhai 1.25.0
Perhaps similar to #11, but that issue was made way before this version so I am unsure if these are the same.

The same issue also seems to affect https://github.com/rhaiscript/rhai-url so I could open an issue there as well if that would be appropriate.

System details (however, I reproduce this consistently in the GitHub CI):
- Fedora 43
- Cargo and rustc 1.96.0 (installed via Rustup)

Logs:

<details>

```rust
error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:16:46
   |
16 |     pub fn new(url: &str) -> Result<Url, Box<EvalAltResult>> {
   |                                              ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
16 |     pub fn new<EvalAltResult>(url: &str) -> Result<Url, Box<EvalAltResult>> {
   |               +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:17:43
   |
17 |         Url::parse(url).map_err(|e| Box::<EvalAltResult>::from(e.to_string()))
   |                                           ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
16 |     pub fn new<EvalAltResult>(url: &str) -> Result<Url, Box<EvalAltResult>> {
   |               +++++++++++++++

error[E0425]: cannot find type `ImmutableString` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:29:35
   |
29 |     pub fn href(url: &mut Url) -> ImmutableString {
   |                                   ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:42:37
   |
42 |     pub fn scheme(url: &mut Url) -> ImmutableString {
   |                                     ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:82:37
   |
82 |     pub fn domain(url: &mut Url) -> ImmutableString {
   |                                     ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:95:35
   |
95 |     pub fn path(url: &mut Url) -> ImmutableString {
   |                                   ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:114:36
    |
114 |     pub fn query(url: &mut Url) -> ImmutableString {
    |                                    ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:146:39
    |
146 |     pub fn fragment(url: &mut Url) -> ImmutableString {
    |                                       ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:178:35
    |
178 |     pub fn hash(url: &mut Url) -> ImmutableString {
    |                                   ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:291:51
    |
291 |     pub fn query_get(url: &mut Url, key: &str) -> ImmutableString {
    |                                                   ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:329:40
    |
329 |     pub fn to_string(url: &mut Url) -> ImmutableString {
    |                                        ^^^^^^^^^^^^^^^ not found in this scope

error[E0433]: cannot find type `ImmutableString` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:293:33
    |
293 |             Some((_, value)) => ImmutableString::from(value.as_ref()),
    |                                 ^^^^^^^^^^^^^^^ use of undeclared type `ImmutableString`

error[E0433]: cannot find type `ImmutableString` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:294:21
    |
294 |             None => ImmutableString::from(""),
    |                     ^^^^^^^^^^^^^^^ use of undeclared type `ImmutableString`

error[E0433]: cannot find type `ImmutableString` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/url.rs:314:31
    |
314 |             .map(|(_, value)| ImmutableString::from(value.as_ref()).into())
    |                               ^^^^^^^^^^^^^^^ use of undeclared type `ImmutableString`

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:10:56
   |
10 |     pub fn create_dir(path: PathBuf) -> Result<(), Box<EvalAltResult>> {
   |                                                        ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
10 |     pub fn create_dir<EvalAltResult>(path: PathBuf) -> Result<(), Box<EvalAltResult>> {
   |                      +++++++++++++++

error[E0425]: cannot find type `NativeCallContext` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:17:14
   |
17 |         ctx: NativeCallContext,
   |              ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:18:19
   |
18 |         path_raw: ImmutableString,
   |                   ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:19:25
   |
19 |     ) -> Result<(), Box<EvalAltResult>> {
   |                         ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
16 |     pub fn create_dir_str<EvalAltResult>(
   |                          +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:32:56
   |
32 |     pub fn remove_dir(path: PathBuf) -> Result<(), Box<EvalAltResult>> {
   |                                                        ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
32 |     pub fn remove_dir<EvalAltResult>(path: PathBuf) -> Result<(), Box<EvalAltResult>> {
   |                      +++++++++++++++

error[E0425]: cannot find type `NativeCallContext` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:39:14
   |
39 |         ctx: NativeCallContext,
   |              ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:40:19
   |
40 |         path_raw: ImmutableString,
   |                   ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:41:25
   |
41 |     ) -> Result<(), Box<EvalAltResult>> {
   |                         ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
38 |     pub fn remove_dir_str<EvalAltResult>(
   |                          +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:53:63
   |
53 |     pub fn open_dir(path: PathBuf) -> Result<rhai::Array, Box<EvalAltResult>> {
   |                                                               ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
53 |     pub fn open_dir<EvalAltResult>(path: PathBuf) -> Result<rhai::Array, Box<EvalAltResult>> {
   |                    +++++++++++++++

error[E0425]: cannot find type `NativeCallContext` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:66:14
   |
66 |         ctx: NativeCallContext,
   |              ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:67:19
   |
67 |         path_raw: ImmutableString,
   |                   ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:68:34
   |
68 |     ) -> Result<rhai::Array, Box<EvalAltResult>> {
   |                                  ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
65 |     pub fn open_dir_str<EvalAltResult>(
   |                        +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:10:74
   |
10 | fn convert_to_int(val: impl TryInto<rhai::INT>) -> Result<rhai::INT, Box<EvalAltResult>> {
   |                                                                          ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
10 | fn convert_to_int<EvalAltResult>(val: impl TryInto<rhai::INT>) -> Result<rhai::INT, Box<EvalAltResult>> {
   |                  +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:30:63
   |
30 |     pub fn open_file(path: PathBuf) -> Result<SharedFile, Box<EvalAltResult>> {
   |                                                               ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
30 |     pub fn open_file<EvalAltResult>(path: PathBuf) -> Result<SharedFile, Box<EvalAltResult>> {
   |                     +++++++++++++++

error[E0425]: cannot find type `NativeCallContext` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:37:14
   |
37 |         ctx: NativeCallContext,
   |              ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:38:19
   |
38 |         path_raw: ImmutableString,
   |                   ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:39:33
   |
39 |     ) -> Result<SharedFile, Box<EvalAltResult>> {
   |                                 ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
36 |     pub fn open_file_str<EvalAltResult>(
   |                         +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:62:33
   |
62 |     ) -> Result<SharedFile, Box<EvalAltResult>> {
   |                                 ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
59 |     pub fn open_file_with_opts<EvalAltResult>(
   |                               +++++++++++++++

error[E0425]: cannot find type `NativeCallContext` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:85:14
   |
85 |         ctx: NativeCallContext,
   |              ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:86:19
   |
86 |         path_raw: ImmutableString,
   |                   ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:88:33
   |
88 |     ) -> Result<SharedFile, Box<EvalAltResult>> {
   |                                 ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
84 |     pub fn open_file_with_opts_str<EvalAltResult>(
   |                                   +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:100:57
    |
100 |     pub fn remove_file(path: PathBuf) -> Result<(), Box<EvalAltResult>> {
    |                                                         ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
100 |     pub fn remove_file<EvalAltResult>(path: PathBuf) -> Result<(), Box<EvalAltResult>> {
    |                       +++++++++++++++

error[E0425]: cannot find type `NativeCallContext` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:107:14
    |
107 |         ctx: NativeCallContext,
    |              ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `ImmutableString` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:108:19
    |
108 |         path_raw: ImmutableString,
    |                   ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:109:25
    |
109 |     ) -> Result<(), Box<EvalAltResult>> {
    |                         ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
106 |     pub fn remove_file_str<EvalAltResult>(
    |                           +++++++++++++++

error[E0425]: cannot find type `NativeCallContext` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:120:14
    |
120 |         ctx: NativeCallContext,
    |              ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:122:29
    |
122 |     ) -> Result<String, Box<EvalAltResult>> {
    |                             ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
119 |     pub fn read_to_string<EvalAltResult>(
    |                          +++++++++++++++

error[E0425]: cannot find type `NativeCallContext` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:132:14
    |
132 |         ctx: NativeCallContext,
    |              ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:135:29
    |
135 |     ) -> Result<String, Box<EvalAltResult>> {
    |                             ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
131 |     pub fn read_to_string_with_len<EvalAltResult>(
    |                                   +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:172:32
    |
172 |     ) -> Result<rhai::INT, Box<EvalAltResult>> {
    |                                ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
169 |     pub fn write_with_string<EvalAltResult>(
    |                             +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:184:81
    |
184 |     pub fn seek(file: &mut SharedFile, pos: rhai::INT) -> Result<rhai::INT, Box<EvalAltResult>> {
    |                                                                                 ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
184 |     pub fn seek<EvalAltResult>(file: &mut SharedFile, pos: rhai::INT) -> Result<rhai::INT, Box<EvalAltResult>> {
    |                +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:193:69
    |
193 |     pub fn position(file: &mut SharedFile) -> Result<rhai::INT, Box<EvalAltResult>> {
    |                                                                     ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
193 |     pub fn position<EvalAltResult>(file: &mut SharedFile) -> Result<rhai::INT, Box<EvalAltResult>> {
    |                    +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:202:66
    |
202 |     pub fn bytes(file: &mut SharedFile) -> Result<rhai::INT, Box<EvalAltResult>> {
    |                                                                  ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
202 |     pub fn bytes<EvalAltResult>(file: &mut SharedFile) -> Result<rhai::INT, Box<EvalAltResult>> {
    |                 +++++++++++++++

error[E0425]: cannot find type `NativeCallContext` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:216:18
    |
216 |             ctx: NativeCallContext,
    |                  ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:218:31
    |
218 |         ) -> Result<Blob, Box<EvalAltResult>> {
    |                               ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
215 |         pub fn read_to_blob<EvalAltResult>(
    |                            +++++++++++++++

error[E0425]: cannot find type `NativeCallContext` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:225:18
    |
225 |             ctx: NativeCallContext,
    |                  ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:228:31
    |
228 |         ) -> Result<Blob, Box<EvalAltResult>> {
    |                               ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
224 |         pub fn read_to_blob_with_len<EvalAltResult>(
    |                                     +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:259:36
    |
259 |         ) -> Result<rhai::INT, Box<EvalAltResult>> {
    |                                    ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
256 |         pub fn read_from_file<EvalAltResult>(
    |                              +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
   --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/file.rs:271:36
    |
271 |         ) -> Result<rhai::INT, Box<EvalAltResult>> {
    |                                    ^^^^^^^^^^^^^ not found in this scope
    |
help: you might be missing a type parameter
    |
268 |         pub fn write_to_file<EvalAltResult>(
    |                             +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/path.rs:20:41
   |
20 |     pub fn cwd() -> Result<PathBuf, Box<EvalAltResult>> {
   |                                         ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
20 |     pub fn cwd<EvalAltResult>() -> Result<PathBuf, Box<EvalAltResult>> {
   |               +++++++++++++++

error[E0425]: cannot find type `EvalAltResult` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/path.rs:32:68
   |
32 |     pub fn canonicalize(path: &mut PathBuf) -> Result<PathBuf, Box<EvalAltResult>> {
   |                                                                    ^^^^^^^^^^^^^ not found in this scope
   |
help: you might be missing a type parameter
   |
32 |     pub fn canonicalize<EvalAltResult>(path: &mut PathBuf) -> Result<PathBuf, Box<EvalAltResult>> {
   |                        +++++++++++++++

error[E0433]: cannot find type `Dynamic` in this scope
  --> /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/dir.rs:57:26
   |
57 |                 .map(|e| Dynamic::from(e.path()))
   |                          ^^^^^^^ use of undeclared type `Dynamic`

   Compiling promptly v0.3.1
     Running `/home/roachy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name promptly --edition=2018 /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/promptly-0.3.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=162 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("default", "nightly", "url"))' -C metadata=353fa05479a75f8a -C extra-filename=-7987c881f3453a07 --out-dir /home/roachy/git/anda/deps/target/debug/deps -L dependency=/home/roachy/git/anda/deps/target/debug/deps --extern rustyline=/home/roachy/git/anda/deps/target/debug/deps/librustyline-78c257b87d9c44b5.rmeta --cap-lints allow`
Some errors have detailed explanations: E0425, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `rhai-url` (lib) due to 14 previous errors

Caused by:
  process didn't exit successfully: `/home/roachy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name rhai_url --edition=2021 /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-url-0.0.5/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=162 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="array"' --cfg 'feature="default"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("array", "default", "metadata"))' -C metadata=8b56792cfc4a506e -C extra-filename=-e0653a92e8c060e0 --out-dir /home/roachy/git/anda/deps/target/debug/deps -L dependency=/home/roachy/git/anda/deps/target/debug/deps --extern rhai=/home/roachy/git/anda/deps/target/debug/deps/librhai-d9ac648fa279c1e4.rmeta --extern url=/home/roachy/git/anda/deps/target/debug/deps/liburl-75f69969138d7a8c.rmeta --cap-lints allow` (exit status: 1)
warning: build failed, waiting for other jobs to finish...
error: could not compile `rhai-fs` (lib) due to 42 previous errors

Caused by:
  process didn't exit successfully: `/home/roachy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name rhai_fs --edition=2021 /home/roachy/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rhai-fs-0.1.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=162 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("default", "metadata", "no_index", "sync"))' -C metadata=4d33bd739e5dac1a -C extra-filename=-a88f7255e177ae95 --out-dir /home/roachy/git/anda/deps/target/debug/deps -L dependency=/home/roachy/git/anda/deps/target/debug/deps --extern rhai=/home/roachy/git/anda/deps/target/debug/deps/librhai-d9ac648fa279c1e4.rmeta --cap-lints allow` (exit status: 1)
```

</details>

### LINKED ISSUE #1098: Version 1.25.0 had undocumented breaking change
> This removal was a breaking change as dependent crates could import these items via `rhai::plugin`. For example [apollo-router](https://github.com/apollographql/router/blob/dev/apollo-router/src/plugins/rhai/engine/mod.rs) are (and have for quite some time) been relying on this import path. 

 _Originally posted by @Abendrill in [475d45e](https://github.com/rhaiscript/rhai/commit/475d45ee294aa4cf95c7e07bdca2934dca10e20b#r186669870)_

Is this an unintended breaking change? If so, could it be re-added?
Or if it is, could that be reflected in the version?

----

**Note:** I'm doing a custom build with Rust plugins. Therefore, because `apollo-router` is used as a library, your `Cargo.lock` file [is ignored](https://doc.rust-lang.org/1.71.1/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries). Therefore, `rhai` is resolved to anything that should be semver compatible with the version you've specified (`1.23.6`). That's why cargo by default resolves `rhai@1.25.0` for me and not `rhai@1.23.6`.

### PR DESCRIPTION
**Pull request by Abendrill**
This PR re-introduce some re-exports that were [removed from `rhai::plugin` in 1.25.0](https://github.com/rhaiscript/rhai/commit/475d45ee294aa4cf95c7e07bdca2934dca10e20b#r186669870).

This removal was an unintended breaking change despite the items still being available, since dependent crates may have used this import path. In-fact, this did break [`apollo-router`](https://github.com/apollographql/router/issues/9528) when used as a library.

Fixes #1098

### CODE REVIEW

**Comment by schungx** [comment]
The formatting CI is failing...  Perhaps you need to do a `cargo fmt`.

**Comment by Abendrill** [comment]
My bad, I've applied formatting now.

❗ Also two ui_tests failed. rustc decided to use `std::iter::Iterator` instead of just `Iterator`. I'm not sure why. I just opted to update the expected output. Are you @schungx ok with this?

**Comment by schungx** [comment]
I think you should remove the fixes to the unrelated tests as it'd just clutter up the PR. 

I'd put in another PR later on to fix the test outputs. 

Don't worry if they fail at this point.

**Comment by Abendrill** [comment]
Alright, will do.

**Comment by schungx** [comment]
Yes because Rust 1.90 has just come out and there would be more test outputs that need to update anyway.

**Comment by Abendrill** [comment]
Removed the ui_test changes now!

**Comment by Abendrill** [comment]
Thanks for quick and responsive collab @schungx! 🚀
